name: Docker

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Docker image (arm64)
        id: container-build-and-push-arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.arm64
          push: true
          platforms: linux/arm64/v8
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}, ${{ env.REGISTRY }}/${{ github.repository }}:latest, ${{ github.repository }}:${{ github.ref_name }}, ${{ github.repository }}:latest
        
      
      - name: Build and push Docker image (x64)
        id: container-build-and-push-x64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.x64
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}, ${{ env.REGISTRY }}/${{ github.repository }}:latest, ${{ github.repository }}:${{ github.ref_name }}, ${{ github.repository }}:latest
        